
# this docker compose file contains the instructions to launch and orchestrate the following containers on the linux servers:
# - neo4j database for environment data
# - neo4j dataserver for environment data
# - weather data collection application

name: cabinenv

services:
  weatherdata:
    image: cabindock/weatherdata:latest-amd
    container_name: weatherdata
    environment:
      - NEO4J_DATA_API_URL=http://neo4j-env-dataserver:8000
      - NATS_SERVER=nats://nats-server-1:4222
      - LOG_LEVEL=ERROR
    networks:
      - cabin-network
    depends_on:
      - neo4j-db
      - neo4j-env-dataserver

  neo4j-env-dataserver:
    image: cabindock/neo4j-env-dataserver:latest-amd
    container_name: neo4j-env-dataserver
    ports:
      - "8000:8000"
    environment:
      - NEO4J_ENV_CONNECTION_STR=bolt://neo4j-db:7687
      - LOG_LEVEL=ERROR
    networks:
      - cabin-network
    depends_on:
      - neo4j-db

  neo4j-db:
    image: neo4j:5.21.0
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - /mnt/neo4j/environment/data:/data
    networks:
      - cabin-network

networks:
  cabin-network:
    external: true
