
name: cssnats

services:
  nats-server-1:
    image: nats:2.12.8-alpine
    container_name: nats-server-1
    restart: unless-stopped
    volumes:
      - ./Nats/nats-server-1-arm.conf:/etc/nats/nats-server-1-arm.conf:ro
    command: ["-c", "/etc/nats/nats-server-1-arm.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - cabin-network

  nats-server-2:
    image: nats:2.12.8-alpine
    container_name: nats-server-2
    restart: unless-stopped
    volumes:
      - ./Nats/nats-server-2-arm.conf:/etc/nats/nats-server-2-arm.conf:ro
    command: ["-c", "/etc/nats/nats-server-2-arm.conf"]
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    networks:
      - cabin-network

networks:
  cabin-network:
    external: true
