# Stage 1: builder
FROM python 3.13-slim-trixie as builder

WORKDIR /build

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt

# Stage 2: runtime
FROM python 3.13-slim-trixie as runtime

WORKDIR /app

RUN apt-get update && rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

# copy just the required application files and directories
COPY ./.env .
COPY ./EnvironmentSensors ./EnvironmentSensors
COPY ./SensorDataMgmt ./SensorDataMgmt
COPY ./utilities ./utilities

USER nobody

CMD ["python", "-m", "main.py"]